@baseUrl = http://localhost:3000/api/v1
@courtId = b0fc8740-a515-4502-b1d0-325b13e6a524
@reservationId = 417f7958-f757-429a-9b27-3d4df20e4dcf

# Após executar o Passo 1, cole o token gerado abaixo:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYWFhYWFhYS1hYWFhLWFhYWEtYWFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImpvYW9AYWNpbWFyLmNvbSIsImlhdCI6MTc4Mjk0NzQ1OCwiZXhwIjoxNzgzMDMzODU4fQ.3sX-qxiUub9IfvFkaDr59whfwsrjZmGaFc9T4Uu8cwc

### 1. Autenticação (Login)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "joao@acimar.com",
  "password": "senha123"
}

### 2. Criar uma reserva
POST {{baseUrl}}/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "court_id": "{{courtId}}",
  "customer_name": "João Teste",
  "customer_cpf": "12345678901",
  "reservation_date": "2026-07-30",
  "start_time": "11:00:00",
  "end_time": "12:00:00"
}

### 3. Consultar reservas do dia
GET {{baseUrl}}/reservations?court_id={{courtId}}&date=2026-07-30
Authorization: Bearer {{token}}

### 4. Alterar status para pago
PATCH {{baseUrl}}/reservations/{{reservationId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "paid"
}

### 5. Deletar reserva
DELETE {{baseUrl}}/reservations/{{reservationId}}
Authorization: Bearer {{token}}








